# ABI Frameworks — Medicare Part B Wound Care Billing Pipeline

**Hackathon:** Pulse Foundry AI NYC x ABI Frameworks · June 28, 2026  
**Team:** Richa Shiny  
**Problem:** Automate the manual triage process that determines which post-acute care patients qualify for wound care billing under Medicare Part B.

---

## What This Notebook Does

This pipeline connects to the ABI Frameworks / PointClickCare mock API and:

1. **Ingests** all 300 patients across 3 facilities
2. **Extracts** wound fields from 4 note formats (SOAP, Prose, Multi-wound, Envive)
3. **Routes** each patient to: `auto_accept` | `flag_for_review` | `reject`
4. **Flags** compliance risks before they become OIG audit problems

### Key Design Decisions
- **ATB retry logic** (IEEE CCNC 2026) — handles the 30% HTTP 429 rate limit without retry storms
- **Payer-aware fast path** — skips 310 unnecessary API calls for non-MCB patients
- **LLM fallback** — uses Claude API for unstructured Envive notes where regex fails
- **Never treats a failed API call as ineligibility** — fetch failures → flag_for_review, not reject
- **9-tier flag system** — ICD-10 mismatch, new admission Stage 3/4, stalled wounds, high visit frequency

---

## Pipeline Architecture

```
PCC API (3 facilities, 300 patients)
    ↓
api_client.py   — ATB congestion-aware retry for HTTP 429
    ↓
ingest.py       — Parallel fetch, payer-aware fast path
    ↓
extract.py      — Regex + LLM extraction from all note formats
    ↓
eligibility.py  — 9-tier compliance flag system, routing decisions
    ↓
eligibility_output.csv  →  Streamlit dashboard
```

---

## Step 0 — Install Dependencies

In [1]:
!pip install requests pandas streamlit anthropic -q

## Step 1 — Load Patient Data

Load the base patient file (demographics only — no clinical data yet).  
300 patients across 3 facilities: Facility A (101), B (102), C (103).  
Payer mix: ~48% MCB (Medicare Part B — our targets), rest HMO/MCA/MCD.

In [2]:
import os
import json

# Load patients from Desktop (moved from Downloads to avoid macOS permission issues)
src = os.path.expanduser('~/Desktop/patients.json')

with open(src, 'r') as f:
    patients = json.load(f)

os.makedirs('data', exist_ok=True)
os.makedirs('output', exist_ok=True)

with open('data/raw_patients.json', 'w') as f:
    json.dump(patients, f)

from collections import Counter
payers = Counter(p['primary_payer_code'] for p in patients)
print(f"Loaded {len(patients)} patients")
print(f"Payer mix: {dict(payers)}")
print(f"MCB eligible (our targets): {payers['MCB']}")
print(f"Working directory: {os.getcwd()}")

Loaded 300 patients
Payer mix: {'MCB': 145, 'HMO': 63, 'MCD': 36, 'MCA': 56}
MCB eligible (our targets): 145
Working directory: /Users/richashiny/Desktop

## Step 2 — API Client with ATB Retry Logic

The PulseFoundry API has a **30% chance of HTTP 429 on every request**.

Standard exponential backoff causes retry storms when multiple threads share a quota.  
We implement an **Adaptive Token Bucket (ATB)** approach from:  
> Farkiani et al. — *"Rethinking HTTP API Rate Limiting: A Client-Side Approach"*  
> IEEE CCNC 2026 — showed 97.3% reduction in 429 errors vs plain backoff.

Key insight: track consecutive 429s as a **congestion signal** and scale wait time proportionally.  
Add **jitter** so parallel threads don't wake up simultaneously (the retry storm problem).

**Two patient ID types (critical gotcha):**
- `patient_id` (string e.g. `FA-001`) → `/diagnoses`, `/coverage`
- `id` (integer e.g. `1`) → `/notes`, `/assessments`

In [3]:
%%writefile api_client.py
import time
import random
import requests
import logging
from typing import Optional

log = logging.getLogger(__name__)
BASE_URL = "https://hackathon.prod.pulsefoundry.ai"
MAX_RETRIES = 8
_consecutive_429s = 0

def _get(endpoint, params):
    global _consecutive_429s
    url = f"{BASE_URL}{endpoint}"
    for attempt in range(MAX_RETRIES):
        try:
            resp = requests.get(url, params=params, timeout=15)
            if resp.status_code == 200:
                _consecutive_429s = 0
                return resp.json(), 'ok'
            if resp.status_code == 429:
                _consecutive_429s += 1
                base_wait = int(resp.headers.get("Retry-After", 2))
                congestion_factor = 1 + (0.5 * _consecutive_429s)
                jitter = random.uniform(0, 1.0)
                wait = (base_wait * congestion_factor) + jitter
                log.warning(f"429 attempt {attempt+1} congestion={_consecutive_429s} wait={wait:.1f}s")
                time.sleep(wait)
                continue
            if resp.status_code == 422:
                return [], 'failed'
            time.sleep((2 ** attempt) + random.uniform(0, 1))
        except requests.RequestException as exc:
            log.error(f"Request error: {exc}")
            time.sleep((2 ** attempt) + random.uniform(0, 1))
    return [], 'failed'

def get_patients(facility_id, since=None):
    params = {"facility_id": facility_id}
    if since:
        params["since"] = since
    return _get("/pcc/patients", params)

def get_diagnoses(patient_id):
    return _get("/pcc/diagnoses", {"patient_id": patient_id})

def get_coverage(patient_id):
    return _get("/pcc/coverage", {"patient_id": patient_id})

def get_notes(internal_id, since=None):
    params = {"patient_id": internal_id}
    if since:
        params["since"] = since
    return _get("/pcc/notes", params)

def get_assessments(internal_id, since=None):
    params = {"patient_id": internal_id}
    if since:
        params["since"] = since
    return _get("/pcc/assessments", params)

Writing api_client.py

## Step 3 — Data Ingestion Pipeline

Fetches all 5 endpoints for each patient using a thread pool.

**Payer-aware fast path optimization:**  
155 of 300 patients are non-MCB (HMO/MCA/MCD).  
We skip notes + assessments for them — saves ~310 API calls.  
Still fetch coverage to catch payer_code errors.

**Fetch status tracking:**  
Every endpoint records `ok` | `failed` | `skipped`.  
A failed fetch ≠ ineligible patient — it means the data is unavailable.  
Failed fetch → `flag_for_review`, never `reject`.

In [4]:
%%writefile ingest.py
import json
import logging
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
from api_client import get_patients, get_diagnoses, get_coverage, get_notes, get_assessments

log = logging.getLogger(__name__)
FACILITIES = [101, 102, 103]
NON_MCB_PAYERS = {"HMO", "MCA", "MCD"}
DATA_DIR = Path("data")
DATA_DIR.mkdir(exist_ok=True)

def _fetch_one_patient(patient):
    pid_str = patient["patient_id"]
    pid_int = patient["id"]
    payer = patient.get("primary_payer_code", "")
    diagnoses, dx_status = get_diagnoses(pid_str)
    coverage, cov_status = get_coverage(pid_str)
    if payer in NON_MCB_PAYERS:
        return {**patient, "diagnoses": diagnoses, "coverage": coverage,
                "notes": [], "assessments": [],
                "fetch_status": {"diagnoses": dx_status, "coverage": cov_status,
                                 "notes": "skipped", "assessments": "skipped"}}
    notes, notes_status = get_notes(pid_int)
    assessments, assess_status = get_assessments(pid_int)
    return {**patient, "diagnoses": diagnoses, "coverage": coverage,
            "notes": notes, "assessments": assessments,
            "fetch_status": {"diagnoses": dx_status, "coverage": cov_status,
                             "notes": notes_status, "assessments": assess_status}}

def ingest_facility(facility_id, since=None):
    patients_data, status = get_patients(facility_id, since=since)
    if status == 'failed':
        log.error(f"Could not fetch patients for facility {facility_id}")
        return []
    log.info(f"Facility {facility_id}: {len(patients_data)} patients")
    enriched = []
    with ThreadPoolExecutor(max_workers=4) as pool:
        futures = {pool.submit(_fetch_one_patient, p): p for p in patients_data}
        for future in as_completed(futures):
            try:
                enriched.append(future.result())
            except Exception as exc:
                log.error(f"Failed: {exc}")
    return enriched

def run_ingestion(since=None):
    all_patients = []
    for fid in FACILITIES:
        all_patients.extend(ingest_facility(fid, since=since))
    log.info(f"Total: {len(all_patients)} patients")
    with open(DATA_DIR / "raw_patients.json", "w") as f:
        json.dump(all_patients, f, indent=2, default=str)
    return all_patients

Writing ingest.py

## Step 4 — Run Full API Ingestion

Hits the live API. Takes 5-10 minutes due to rate limiting.  
Saves enriched data (demographics + clinical) to `data/raw_patients.json`.  
Use `--use-cached` in subsequent runs to skip API calls.

In [5]:
import logging
logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s %(levelname)s %(message)s")

from ingest import run_ingestion

print("Starting API ingestion across 3 facilities...")
print("Rate limit warnings are expected and handled automatically.")
print()

patients_full = run_ingestion()

print()
print(f"Ingestion complete: {len(patients_full)} patients")
print(f"MCB patients (full fetch): {sum(1 for p in patients_full if p.get('primary_payer_code')=='MCB')}")
print(f"Patients with notes: {sum(1 for p in patients_full if p.get('notes'))}")
print(f"Patients with assessments: {sum(1 for p in patients_full if p.get('assessments'))}")

# Update patients variable for extraction step
patients = patients_full

2026-06-28 14:06:46,151 INFO Facility 101: 120 patients

Starting API ingestion across 3 facilities...
Rate limit warnings are expected and handled automatically.

2026-06-28 14:06:46,265 WARNING 429 attempt 1 congestion=1 wait=3.3s
2026-06-28 14:06:46,266 WARNING 429 attempt 1 congestion=2 wait=4.6s
2026-06-28 14:06:46,282 WARNING 429 attempt 1 congestion=1 wait=5.4s
2026-06-28 14:06:46,994 WARNING 429 attempt 1 congestion=1 wait=6.5s
2026-06-28 14:06:50,163 WARNING 429 attempt 1 congestion=1 wait=1.5s
2026-06-28 14:06:50,981 WARNING 429 attempt 2 congestion=2 wait=10.0s
2026-06-28 14:06:51,795 WARNING 429 attempt 2 congestion=3 wait=7.6s
2026-06-28 14:06:52,373 WARNING 429 attempt 1 congestion=1 wait=7.9s
2026-06-28 14:06:55,560 WARNING 429 attempt 1 congestion=1 wait=2.3s
2026-06-28 14:06:58,927 WARNING 429 attempt 1 congestion=1 wait=8.2s
2026-06-28 14:06:59,547 WARNING 429 attempt 3 congestion=2 wait=6.5s
2026-06-28 14:07:00,604 WARNING 429 attempt 1 congestion=1 wait=8.4s
2026-06-28 14:07:01,623 WARNING 429 attempt 1 congestion=1 wait=4.9s
2026-06-28 14:07:08,002 WARNING 429 attempt 1 congestion=1 wait=6.3s
2026-06-28 14:07:08,113 WARNING 429 attempt 1 congestion=2 wait=6.5s
2026-06-28 14:07:09,227 WARNING 429 attempt 2 congestion=1 wait=7.7s
2026-06-28 14:07:09,413 WARNING 429 attempt 1 congestion=1 wait=7.7s
2026-06-28 14:07:14,648 WARNING 429 attempt 1 congestion=1 wait=4.0s
2026-06-28 14:07:14,852 WARNING 429 attempt 1 congestion=1 wait=5.1s
2026-06-28 14:07:17,176 WARNING 429 attempt 3 congestion=2 wait=8.6s
2026-06-28 14:07:17,602 WARNING 429 attempt 1 congestion=1 wait=4.8s
2026-06-28 14:07:18,795 WARNING 429 attempt 1 congestion=1 wait=1.9s
2026-06-28 14:07:20,042 WARNING 429 attempt 2 congestion=2 wait=6.2s
2026-06-28 14:07:20,786 WARNING 429 attempt 2 congestion=3 wait=8.3s
2026-06-28 14:07:22,663 WARNING 429 attempt 1 congestion=1 wait=3.5s
2026-06-28 14:07:26,030 WARNING 429 attempt 1 congestion=1 wait=6.8s
2026-06-28 14:07:26,508 WARNING 429 attempt 1 congestion=1 wait=8.2s
2026-06-28 14:07:26,585 WARNING 429 attempt 1 congestion=2 wait=2.6s
2026-06-28 14:07:29,132 WARNING 429 attempt 3 congestion=3 wait=8.3s
2026-06-28 14:07:29,785 WARNING 429 attempt 1 congestion=1 wait=2.0s
2026-06-28 14:07:31,829 WARNING 429 attempt 2 congestion=2 wait=2.7s
2026-06-28 14:07:34,179 WARNING 429 attempt 1 congestion=1 wait=6.6s
2026-06-28 14:07:34,734 WARNING 429 attempt 3 congestion=2 wait=10.2s
2026-06-28 14:07:34,797 WARNING 429 attempt 2 congestion=3 wait=7.6s
2026-06-28 14:07:37,495 WARNING 429 attempt 4 congestion=4 wait=12.6s
2026-06-28 14:07:41,626 WARNING 429 attempt 1 congestion=1 wait=2.2s
2026-06-28 14:07:42,875 WARNING 429 attempt 1 congestion=1 wait=3.4s
2026-06-28 14:07:43,957 WARNING 429 attempt 1 congestion=1 wait=5.3s
2026-06-28 14:07:45,210 WARNING 429 attempt 1 congestion=1 wait=3.0s
2026-06-28 14:07:46,700 WARNING 429 attempt 1 congestion=1 wait=3.8s
2026-06-28 14:07:48,397 WARNING 429 attempt 2 congestion=2 wait=8.3s
2026-06-28 14:07:49,358 WARNING 429 attempt 2 congestion=3 wait=3.2s
2026-06-28 14:07:50,592 WARNING 429 attempt 2 congestion=1 wait=1.7s
2026-06-28 14:07:50,702 WARNING 429 attempt 1 congestion=2 wait=8.1s
2026-06-28 14:07:52,593 WARNING 429 attempt 3 congestion=1 wait=8.2s
2026-06-28 14:07:52,691 WARNING 429 attempt 1 congestion=2 wait=4.1s
2026-06-28 14:07:56,923 WARNING 429 attempt 2 congestion=3 wait=5.1s
2026-06-28 14:07:56,924 WARNING 429 attempt 3 congestion=4 wait=6.5s
2026-06-28 14:07:59,273 WARNING 429 attempt 1 congestion=1 wait=7.9s
2026-06-28 14:08:02,239 WARNING 429 attempt 1 congestion=1 wait=6.5s
2026-06-28 14:08:05,077 WARNING 429 attempt 1 congestion=1 wait=5.2s
2026-06-28 14:08:05,716 WARNING 429 attempt 1 congestion=1 wait=6.3s
2026-06-28 14:08:08,526 WARNING 429 attempt 1 congestion=1 wait=3.4s
2026-06-28 14:08:10,012 WARNING 429 attempt 1 congestion=1 wait=6.1s
2026-06-28 14:08:11,376 WARNING 429 attempt 1 congestion=1 wait=5.2s
2026-06-28 14:08:12,006 WARNING 429 attempt 2 congestion=2 wait=4.4s
2026-06-28 14:08:12,254 WARNING 429 attempt 1 congestion=1 wait=3.5s
2026-06-28 14:08:16,177 WARNING 429 attempt 2 congestion=1 wait=2.2s
2026-06-28 14:08:16,178 WARNING 429 attempt 1 congestion=2 wait=6.2s
2026-06-28 14:08:17,397 WARNING 429 attempt 1 congestion=1 wait=8.2s
2026-06-28 14:08:17,410 WARNING 429 attempt 1 congestion=2 wait=11.0s
2026-06-28 14:08:19,357 WARNING 429 attempt 1 congestion=1 wait=4.7s
2026-06-28 14:08:22,838 WARNING 429 attempt 1 congestion=1 wait=1.5s
2026-06-28 14:08:24,265 WARNING 429 attempt 1 congestion=1 wait=6.3s
2026-06-28 14:08:25,101 WARNING 429 attempt 1 congestion=1 wait=6.2s
2026-06-28 14:08:25,729 WARNING 429 attempt 2 congestion=2 wait=4.2s
2026-06-28 14:08:28,943 WARNING 429 attempt 1 congestion=1 wait=2.4s
2026-06-28 14:08:30,574 WARNING 429 attempt 1 congestion=1 wait=5.0s
2026-06-28 14:08:30,587 WARNING 429 attempt 2 congestion=2 wait=8.2s
2026-06-28 14:08:31,430 WARNING 429 attempt 2 congestion=3 wait=5.4s
2026-06-28 14:08:31,590 WARNING 429 attempt 1 congestion=1 wait=6.8s
2026-06-28 14:08:36,062 WARNING 429 attempt 1 congestion=1 wait=2.5s
2026-06-28 14:08:37,202 WARNING 429 attempt 1 congestion=1 wait=7.7s
2026-06-28 14:08:38,498 WARNING 429 attempt 2 congestion=2 wait=8.5s
2026-06-28 14:08:39,336 WARNING 429 attempt 1 congestion=1 wait=4.0s
2026-06-28 14:08:39,631 WARNING 429 attempt 1 congestion=1 wait=5.2s
2026-06-28 14:08:43,932 WARNING 429 attempt 1 congestion=1 wait=8.1s
2026-06-28 14:08:44,949 WARNING 429 attempt 2 congestion=2 wait=2.7s
2026-06-28 14:08:45,464 WARNING 429 attempt 1 congestion=1 wait=2.4s
2026-06-28 14:08:47,066 WARNING 429 attempt 3 congestion=2 wait=2.8s
2026-06-28 14:08:47,827 WARNING 429 attempt 1 congestion=1 wait=4.6s
2026-06-28 14:08:48,242 WARNING 429 attempt 1 congestion=1 wait=6.4s
2026-06-28 14:08:50,136 WARNING 429 attempt 1 congestion=1 wait=2.5s
2026-06-28 14:08:52,244 WARNING 429 attempt 1 congestion=1 wait=2.5s
2026-06-28 14:08:52,747 WARNING 429 attempt 1 congestion=1 wait=6.1s
2026-06-28 14:08:52,842 WARNING 429 attempt 1 congestion=1 wait=6.5s
2026-06-28 14:08:54,916 WARNING 429 attempt 2 congestion=2 wait=6.1s
2026-06-28 14:08:54,916 WARNING 429 attempt 2 congestion=3 wait=3.1s
2026-06-28 14:08:58,270 WARNING 429 attempt 1 congestion=1 wait=3.3s
2026-06-28 14:08:59,067 WARNING 429 attempt 1 congestion=1 wait=7.0s
2026-06-28 14:08:59,802 WARNING 429 attempt 1 congestion=1 wait=6.2s
2026-06-28 14:09:01,292 WARNING 429 attempt 1 congestion=1 wait=2.4s
2026-06-28 14:09:02,847 WARNING 429 attempt 1 congestion=1 wait=4.0s
2026-06-28 14:09:04,733 WARNING 429 attempt 1 congestion=1 wait=3.3s
2026-06-28 14:09:06,497 WARNING 429 attempt 1 congestion=1 wait=5.1s
2026-06-28 14:09:07,476 WARNING 429 attempt 1 congestion=1 wait=8.4s
2026-06-28 14:09:07,783 WARNING 429 attempt 1 congestion=1 wait=8.2s
2026-06-28 14:09:09,484 WARNING 429 attempt 1 congestion=1 wait=4.5s
2026-06-28 14:09:11,704 WARNING 429 attempt 2 congestion=2 wait=10.2s
2026-06-28 14:09:14,162 WARNING 429 attempt 1 congestion=1 wait=2.3s
2026-06-28 14:09:16,122 WARNING 429 attempt 2 congestion=2 wait=4.5s
2026-06-28 14:09:16,505 WARNING 429 attempt 1 congestion=1 wait=3.2s
2026-06-28 14:09:16,507 WARNING 429 attempt 2 congestion=2 wait=10.5s
2026-06-28 14:09:20,992 WARNING 429 attempt 3 congestion=1 wait=1.5s
2026-06-28 14:09:21,448 WARNING 429 attempt 1 congestion=1 wait=6.1s
2026-06-28 14:09:22,045 WARNING 429 attempt 3 congestion=2 wait=4.4s
2026-06-28 14:09:23,105 WARNING 429 attempt 1 congestion=1 wait=5.3s
2026-06-28 14:09:26,839 WARNING 429 attempt 1 congestion=1 wait=4.6s
2026-06-28 14:09:27,287 WARNING 429 attempt 1 congestion=1 wait=7.8s
2026-06-28 14:09:27,753 WARNING 429 attempt 2 congestion=2 wait=10.8s
2026-06-28 14:09:28,854 WARNING 429 attempt 1 congestion=1 wait=6.4s
2026-06-28 14:09:31,653 WARNING 429 attempt 1 congestion=1 wait=4.6s
2026-06-28 14:09:35,377 WARNING 429 attempt 2 congestion=1 wait=8.0s
2026-06-28 14:09:35,467 WARNING 429 attempt 1 congestion=2 wait=6.1s
2026-06-28 14:09:36,456 WARNING 429 attempt 1 congestion=1 wait=3.5s
2026-06-28 14:09:38,624 WARNING 429 attempt 3 congestion=2 wait=8.2s
2026-06-28 14:09:40,004 WARNING 429 attempt 2 congestion=3 wait=5.3s
2026-06-28 14:09:41,881 WARNING 429 attempt 2 congestion=4 wait=3.6s
2026-06-28 14:09:44,570 WARNING 429 attempt 1 congestion=1 wait=8.0s
2026-06-28 14:09:45,483 WARNING 429 attempt 3 congestion=2 wait=8.1s
2026-06-28 14:09:45,983 WARNING 429 attempt 1 congestion=1 wait=3.7s
2026-06-28 14:09:47,816 WARNING 429 attempt 4 congestion=2 wait=10.6s
2026-06-28 14:09:49,982 WARNING 429 attempt 1 congestion=1 wait=3.2s
2026-06-28 14:09:52,727 WARNING 429 attempt 1 congestion=1 wait=1.5s
2026-06-28 14:09:53,677 WARNING 429 attempt 1 congestion=1 wait=1.8s
2026-06-28 14:09:53,768 WARNING 429 attempt 1 congestion=1 wait=8.2s
2026-06-28 14:09:55,017 WARNING 429 attempt 1 congestion=1 wait=1.5s
2026-06-28 14:09:56,707 WARNING 429 attempt 2 congestion=1 wait=3.4s
2026-06-28 14:09:56,770 WARNING 429 attempt 1 congestion=2 wait=8.6s
2026-06-28 14:09:58,787 WARNING 429 attempt 1 congestion=1 wait=8.0s
2026-06-28 14:10:00,497 WARNING 429 attempt 1 congestion=1 wait=6.2s
2026-06-28 14:10:03,267 WARNING 429 attempt 1 congestion=1 wait=5.5s
2026-06-28 14:10:05,772 WARNING 429 attempt 1 congestion=1 wait=6.3s
2026-06-28 14:10:07,080 WARNING 429 attempt 2 congestion=1 wait=3.6s
2026-06-28 14:10:07,524 WARNING 429 attempt 1 congestion=1 wait=4.5s
2026-06-28 14:10:08,992 WARNING 429 attempt 1 congestion=1 wait=5.3s
2026-06-28 14:10:11,196 WARNING 429 attempt 1 congestion=1 wait=4.5s
2026-06-28 14:10:12,318 WARNING 429 attempt 2 congestion=1 wait=2.1s
2026-06-28 14:10:12,464 WARNING 429 attempt 1 congestion=1 wait=4.6s
2026-06-28 14:10:14,955 WARNING 429 attempt 1 congestion=1 wait=2.4s
2026-06-28 14:10:15,344 WARNING 429 attempt 1 congestion=1 wait=6.9s
2026-06-28 14:10:17,437 WARNING 429 attempt 2 congestion=1 wait=5.2s
2026-06-28 14:10:22,485 WARNING 429 attempt 1 congestion=1 wait=5.4s
2026-06-28 14:10:22,719 WARNING 429 attempt 3 congestion=2 wait=2.8s
2026-06-28 14:10:28,359 INFO Facility 102: 90 patients
2026-06-28 14:10:28,541 WARNING 429 attempt 1 congestion=1 wait=3.8s
2026-06-28 14:10:29,006 WARNING 429 attempt 1 congestion=1 wait=8.0s
2026-06-28 14:10:29,140 WARNING 429 attempt 1 congestion=1 wait=7.9s
2026-06-28 14:10:29,658 WARNING 429 attempt 1 congestion=1 wait=4.7s
2026-06-28 14:10:32,644 WARNING 429 attempt 2 congestion=2 wait=4.3s
2026-06-28 14:10:35,446 WARNING 429 attempt 1 congestion=1 wait=1.9s
2026-06-28 14:10:37,091 WARNING 429 attempt 3 congestion=2 wait=2.3s
2026-06-28 14:10:37,362 WARNING 429 attempt 1 congestion=1 wait=6.8s
2026-06-28 14:10:37,456 WARNING 429 attempt 1 congestion=2 wait=2.7s
2026-06-28 14:10:37,573 WARNING 429 attempt 1 congestion=1 wait=5.0s
2026-06-28 14:10:40,123 WARNING 429 attempt 1 congestion=1 wait=3.3s
2026-06-28 14:10:43,592 WARNING 429 attempt 1 congestion=1 wait=4.8s
2026-06-28 14:10:43,820 WARNING 429 attempt 1 congestion=1 wait=6.9s
2026-06-28 14:10:44,038 WARNING 429 attempt 1 congestion=1 wait=7.0s
2026-06-28 14:10:46,162 WARNING 429 attempt 1 congestion=1 wait=3.7s
2026-06-28 14:10:48,806 WARNING 429 attempt 1 congestion=1 wait=2.3s
2026-06-28 14:10:50,146 WARNING 429 attempt 1 congestion=1 wait=7.7s
2026-06-28 14:10:50,901 WARNING 429 attempt 1 congestion=1 wait=3.5s
2026-06-28 14:10:51,106 WARNING 429 attempt 2 congestion=2 wait=6.1s
2026-06-28 14:10:51,365 WARNING 429 attempt 1 congestion=1 wait=5.4s
2026-06-28 14:10:54,460 WARNING 429 attempt 2 congestion=2 wait=10.1s
2026-06-28 14:10:57,197 WARNING 429 attempt 1 congestion=1 wait=2.5s
2026-06-28 14:10:57,235 WARNING 429 attempt 3 congestion=2 wait=4.2s
2026-06-28 14:10:57,905 WARNING 429 attempt 2 congestion=3 wait=11.0s
2026-06-28 14:10:59,863 WARNING 429 attempt 1 congestion=1 wait=6.3s
2026-06-28 14:11:01,553 WARNING 429 attempt 4 congestion=2 wait=6.5s
2026-06-28 14:11:05,190 WARNING 429 attempt 1 congestion=1 wait=2.0s
2026-06-28 14:11:06,510 WARNING 429 attempt 1 congestion=1 wait=6.1s
2026-06-28 14:11:08,211 WARNING 429 attempt 1 congestion=1 wait=4.6s
2026-06-28 14:11:08,451 WARNING 429 attempt 1 congestion=1 wait=8.0s
2026-06-28 14:11:08,972 WARNING 429 attempt 3 congestion=2 wait=10.9s
2026-06-28 14:11:12,696 WARNING 429 attempt 2 congestion=3 wait=12.5s
2026-06-28 14:11:12,856 WARNING 429 attempt 2 congestion=4 wait=9.5s
2026-06-28 14:11:16,553 WARNING 429 attempt 2 congestion=5 wait=10.6s
2026-06-28 14:11:20,699 WARNING 429 attempt 1 congestion=1 wait=6.2s
2026-06-28 14:11:22,423 WARNING 429 attempt 3 congestion=2 wait=6.5s
2026-06-28 14:11:25,311 WARNING 429 attempt 3 congestion=3 wait=8.3s
2026-06-28 14:11:27,623 WARNING 429 attempt 1 congestion=1 wait=2.3s
2026-06-28 14:11:28,531 WARNING 429 attempt 1 congestion=1 wait=4.9s
2026-06-28 14:11:29,108 WARNING 429 attempt 1 congestion=1 wait=7.9s
2026-06-28 14:11:31,388 WARNING 429 attempt 1 congestion=1 wait=1.6s
2026-06-28 14:11:33,294 WARNING 429 attempt 2 congestion=2 wait=6.6s
2026-06-28 14:11:34,514 WARNING 429 attempt 1 congestion=1 wait=6.7s
2026-06-28 14:11:35,677 WARNING 429 attempt 1 congestion=1 wait=6.2s
2026-06-28 14:11:37,188 WARNING 429 attempt 1 congestion=1 wait=6.5s
2026-06-28 14:11:40,116 WARNING 429 attempt 1 congestion=1 wait=3.5s
2026-06-28 14:11:41,274 WARNING 429 attempt 2 congestion=2 wait=8.8s
2026-06-28 14:11:42,143 WARNING 429 attempt 2 congestion=3 wait=10.5s
2026-06-28 14:11:44,012 WARNING 429 attempt 1 congestion=1 wait=6.7s
2026-06-28 14:11:44,025 WARNING 429 attempt 1 congestion=2 wait=8.4s
2026-06-28 14:11:50,390 WARNING 429 attempt 1 congestion=1 wait=6.9s
2026-06-28 14:11:52,854 WARNING 429 attempt 1 congestion=1 wait=1.7s
2026-06-28 14:11:53,037 WARNING 429 attempt 1 congestion=1 wait=1.9s
2026-06-28 14:11:53,780 WARNING 429 attempt 1 congestion=1 wait=4.5s
2026-06-28 14:11:54,757 WARNING 429 attempt 1 congestion=1 wait=6.2s
2026-06-28 14:11:55,130 WARNING 429 attempt 2 congestion=2 wait=7.0s
2026-06-28 14:11:58,273 WARNING 429 attempt 1 congestion=1 wait=6.5s
2026-06-28 14:11:58,979 WARNING 429 attempt 1 congestion=1 wait=1.6s
2026-06-28 14:12:00,859 WARNING 429 attempt 2 congestion=2 wait=8.8s
2026-06-28 14:12:01,360 WARNING 429 attempt 1 congestion=1 wait=3.1s
2026-06-28 14:12:02,408 WARNING 429 attempt 1 congestion=1 wait=4.9s
2026-06-28 14:12:04,791 WARNING 429 attempt 1 congestion=1 wait=6.2s
2026-06-28 14:12:04,882 WARNING 429 attempt 2 congestion=2 wait=6.3s
2026-06-28 14:12:07,400 WARNING 429 attempt 2 congestion=3 wait=3.4s
2026-06-28 14:12:10,281 WARNING 429 attempt 1 congestion=1 wait=2.2s
2026-06-28 14:12:11,016 WARNING 429 attempt 1 congestion=1 wait=3.0s
2026-06-28 14:12:11,269 WARNING 429 attempt 3 congestion=1 wait=5.2s
2026-06-28 14:12:11,887 WARNING 429 attempt 1 congestion=1 wait=6.2s
2026-06-28 14:12:13,485 WARNING 429 attempt 1 congestion=1 wait=7.5s
2026-06-28 14:12:16,562 WARNING 429 attempt 1 congestion=1 wait=6.7s
2026-06-28 14:12:16,597 WARNING 429 attempt 4 congestion=2 wait=2.9s
2026-06-28 14:12:18,288 WARNING 429 attempt 1 congestion=1 wait=8.3s
2026-06-28 14:12:21,028 WARNING 429 attempt 1 congestion=1 wait=4.9s
2026-06-28 14:12:21,134 WARNING 429 attempt 2 congestion=2 wait=6.1s
2026-06-28 14:12:23,480 WARNING 429 attempt 1 congestion=1 wait=3.7s
2026-06-28 14:12:26,335 WARNING 429 attempt 1 congestion=1 wait=5.3s
2026-06-28 14:12:27,425 WARNING 429 attempt 1 congestion=1 wait=6.2s
2026-06-28 14:12:27,440 WARNING 429 attempt 1 congestion=2 wait=2.0s
2026-06-28 14:12:27,532 WARNING 429 attempt 1 congestion=1 wait=4.0s
2026-06-28 14:12:29,657 WARNING 429 attempt 2 congestion=2 wait=4.6s
2026-06-28 14:12:32,566 WARNING 429 attempt 1 congestion=1 wait=6.8s
2026-06-28 14:12:32,726 WARNING 429 attempt 1 congestion=2 wait=8.4s
2026-06-28 14:12:35,135 WARNING 429 attempt 1 congestion=1 wait=3.9s
2026-06-28 14:12:36,111 WARNING 429 attempt 1 congestion=1 wait=8.0s
2026-06-28 14:12:39,252 WARNING 429 attempt 1 congestion=1 wait=1.7s
2026-06-28 14:12:39,630 WARNING 429 attempt 1 congestion=1 wait=2.4s
2026-06-28 14:12:41,144 WARNING 429 attempt 1 congestion=1 wait=4.7s
2026-06-28 14:12:42,160 WARNING 429 attempt 2 congestion=1 wait=2.0s
2026-06-28 14:12:42,501 WARNING 429 attempt 1 congestion=1 wait=3.7s
2026-06-28 14:12:44,562 WARNING 429 attempt 1 congestion=1 wait=8.4s
2026-06-28 14:12:46,091 WARNING 429 attempt 1 congestion=1 wait=5.2s
2026-06-28 14:12:51,366 WARNING 429 attempt 2 congestion=1 wait=5.4s
2026-06-28 14:12:56,939 WARNING 429 attempt 1 congestion=1 wait=7.6s
2026-06-28 14:13:04,721 INFO Facility 103: 90 patients
2026-06-28 14:13:05,117 WARNING 429 attempt 1 congestion=1 wait=5.1s
2026-06-28 14:13:05,238 WARNING 429 attempt 1 congestion=1 wait=3.3s
2026-06-28 14:13:05,327 WARNING 429 attempt 1 congestion=2 wait=11.0s
2026-06-28 14:13:06,228 WARNING 429 attempt 1 congestion=1 wait=1.5s
2026-06-28 14:13:08,731 WARNING 429 attempt 1 congestion=1 wait=6.7s
2026-06-28 14:13:08,731 WARNING 429 attempt 1 congestion=2 wait=8.9s
2026-06-28 14:13:11,416 WARNING 429 attempt 1 congestion=1 wait=6.9s
2026-06-28 14:13:16,275 WARNING 429 attempt 1 congestion=1 wait=2.5s
2026-06-28 14:13:16,385 WARNING 429 attempt 2 congestion=2 wait=6.1s
2026-06-28 14:13:18,339 WARNING 429 attempt 1 congestion=1 wait=8.1s
2026-06-28 14:13:18,439 WARNING 429 attempt 1 congestion=1 wait=5.0s
2026-06-28 14:13:19,910 WARNING 429 attempt 1 congestion=1 wait=5.5s
2026-06-28 14:13:22,636 WARNING 429 attempt 3 congestion=2 wait=2.3s
2026-06-28 14:13:23,799 WARNING 429 attempt 1 congestion=1 wait=1.8s
2026-06-28 14:13:25,102 WARNING 429 attempt 4 congestion=2 wait=6.9s
2026-06-28 14:13:25,473 WARNING 429 attempt 2 congestion=3 wait=7.7s
2026-06-28 14:13:25,953 WARNING 429 attempt 1 congestion=1 wait=2.5s
2026-06-28 14:13:26,556 WARNING 429 attempt 2 congestion=2 wait=9.0s
2026-06-28 14:13:28,848 WARNING 429 attempt 1 congestion=1 wait=2.2s
2026-06-28 14:13:32,286 WARNING 429 attempt 1 congestion=1 wait=3.5s
2026-06-28 14:13:32,779 WARNING 429 attempt 1 congestion=1 wait=8.1s
2026-06-28 14:13:33,289 WARNING 429 attempt 3 congestion=2 wait=10.1s
2026-06-28 14:13:36,448 WARNING 429 attempt 1 congestion=1 wait=6.0s
2026-06-28 14:13:37,139 WARNING 429 attempt 1 congestion=1 wait=6.7s
2026-06-28 14:13:40,926 WARNING 429 attempt 2 congestion=2 wait=6.9s
2026-06-28 14:13:42,869 WARNING 429 attempt 1 congestion=1 wait=6.8s
2026-06-28 14:13:43,490 WARNING 429 attempt 4 congestion=2 wait=6.1s
2026-06-28 14:13:44,135 WARNING 429 attempt 1 congestion=1 wait=6.9s
2026-06-28 14:13:47,891 WARNING 429 attempt 3 congestion=2 wait=8.9s
2026-06-28 14:13:49,776 WARNING 429 attempt 2 congestion=1 wait=2.3s
2026-06-28 14:13:49,788 WARNING 429 attempt 1 congestion=2 wait=6.9s
2026-06-28 14:13:51,442 WARNING 429 attempt 1 congestion=1 wait=7.8s
2026-06-28 14:13:52,312 WARNING 429 attempt 1 congestion=1 wait=8.1s
2026-06-28 14:13:56,843 WARNING 429 attempt 2 congestion=2 wait=10.8s
2026-06-28 14:13:57,012 WARNING 429 attempt 1 congestion=1 wait=1.5s
2026-06-28 14:13:58,981 WARNING 429 attempt 1 congestion=1 wait=3.9s
2026-06-28 14:13:59,708 WARNING 429 attempt 1 congestion=1 wait=3.7s
2026-06-28 14:14:01,094 WARNING 429 attempt 1 congestion=1 wait=3.7s
2026-06-28 14:14:03,067 WARNING 429 attempt 2 congestion=2 wait=8.6s
2026-06-28 14:14:03,684 WARNING 429 attempt 1 congestion=1 wait=7.8s
2026-06-28 14:14:04,822 WARNING 429 attempt 2 congestion=2 wait=2.3s
2026-06-28 14:14:07,209 WARNING 429 attempt 3 congestion=3 wait=8.2s
2026-06-28 14:14:07,800 WARNING 429 attempt 1 congestion=1 wait=8.1s
2026-06-28 14:14:11,516 WARNING 429 attempt 2 congestion=2 wait=2.5s
2026-06-28 14:14:11,972 WARNING 429 attempt 1 congestion=1 wait=1.8s
2026-06-28 14:14:13,833 WARNING 429 attempt 2 congestion=2 wait=2.9s
2026-06-28 14:14:14,165 WARNING 429 attempt 3 congestion=3 wait=13.0s
2026-06-28 14:14:15,993 WARNING 429 attempt 2 congestion=1 wait=3.9s
2026-06-28 14:14:16,328 WARNING 429 attempt 1 congestion=1 wait=5.0s
2026-06-28 14:14:17,126 WARNING 429 attempt 1 congestion=1 wait=3.4s
2026-06-28 14:14:20,012 WARNING 429 attempt 3 congestion=2 wait=2.1s

Ingestion complete: 300 patients
MCB patients (full fetch): 145
Patients with notes: 145
Patients with assessments: 145

## Step 5 — Wound Data Extraction

Extracts 7 wound fields from each patient's notes and assessments:
`wound_type`, `stage`, `location`, `length_cm`, `width_cm`, `depth_cm`, `drainage`

**4 Note Formats Handled:**
| Format | Description | Extraction Method |
|--------|-------------|-------------------|
| SOAP | Labeled fields (Location:, Length:, etc.) | Regex — high confidence |
| Prose | Shorthand like `Meas 3.1cm x 3.4cm` | Regex — medium confidence |
| Multi-wound | Two wounds described | LLM selects primary wound clinically |
| Envive | Everything in one unstructured paragraph | LLM fallback — medium confidence |

**Priority order:** Structured assessment → SOAP note → Prose → Multi-wound → Envive+LLM

**Assessment format discovery:**  
Real API returns nested `sections → questions → answer` format, not flat keys.  
`_parse_assessment_raw_json()` handles both formats.

**LLM usage (bonus feature):**  
Only fires for Envive notes where regex fails — field-specific, PHI-bounded extraction.  
Grounded in ArcTEX research (Frontiers Digital Health 2025): hybrid regex+LLM achieves 98.67% accuracy.

In [17]:
%%writefile extract.py
import re
import json
import logging

log = logging.getLogger(__name__)

DRAINAGE_MAP = {
    "none": "none", "no drainage": "none", "dry": "none",
    "scant": "light", "minimal": "light", "small": "light", "light": "light",
    "moderate": "moderate", "mod": "moderate",
    "large": "heavy", "heavy": "heavy", "copious": "heavy", "profuse": "heavy",
}

def _normalise_drainage(raw):
    if not raw:
        return None
    raw = raw.lower()
    for key, val in DRAINAGE_MAP.items():
        if key in raw:
            return val
    return None

MEASUREMENT_PATTERNS = [
    # "Length: 3.2 cm  Width: 2.1 cm  Depth: 0.4 cm"
    r"[Ll]ength\s*[:\-]?\s*([0-9]+\.?[0-9]*)\s*cm.*?[Ww]idth\s*[:\-]?\s*([0-9]+\.?[0-9]*)\s*cm.*?[Dd]epth\s*[:\-]?\s*([0-9]+\.?[0-9]*)\s*cm",
    # "Meas 4.2x3.1x1.5cm"
    r"[Mm]eas(?:ures?)?\s*[:\-]?\s*([0-9]+\.?[0-9]*)\s*[xX]\s*([0-9]+\.?[0-9]*)\s*[xX]\s*([0-9]+\.?[0-9]*)\s*cm",
    # "3.2 x 2.1 x 0.4 cm"
    r"([0-9]+\.?[0-9]*)\s*[xX]\s*([0-9]+\.?[0-9]*)\s*[xX]\s*([0-9]+\.?[0-9]*)\s*cm",
    # "3.1 cm x 3.4 cm" (2D only — common in Envive/assessment answers)
    r"([0-9]+\.?[0-9]*)\s*cm\s*[xX]\s*([0-9]+\.?[0-9]*)\s*cm",
    # "Measures 3.1 cm x 3.4 cm"
    r"[Mm]easures?\s+([0-9]+\.?[0-9]*)\s*cm\s*[xX]\s*([0-9]+\.?[0-9]*)\s*cm",
]

def _extract_measurements(text):
    # Try 3D patterns first
    for pat in MEASUREMENT_PATTERNS[:3]:
        m = re.search(pat, text, re.IGNORECASE | re.DOTALL)
        if m:
            return {"length_cm": float(m.group(1)),
                    "width_cm":  float(m.group(2)),
                    "depth_cm":  float(m.group(3))}
    # Try 2D patterns (no depth)
    for pat in MEASUREMENT_PATTERNS[3:]:
        m = re.search(pat, text, re.IGNORECASE | re.DOTALL)
        if m:
            return {"length_cm": float(m.group(1)),
                    "width_cm":  float(m.group(2)),
                    "depth_cm":  None}
    return {"length_cm": None, "width_cm": None, "depth_cm": None}

WOUND_TYPES = [
    (r"pressure\s+ulcer|pressure\s+sore|decubitus",          "pressure_ulcer"),
    (r"diabetic\s+foot\s+ulcer|DFU|neuropathic\s+ulcer",     "diabetic_foot_ulcer"),
    (r"venous\s+(stasis\s+)?ulcer|VSU|venous\s+leg\s+ulcer|venous\s+to", "venous_stasis_ulcer"),
    (r"arterial\s+ulcer|ischemic\s+ulcer",                   "arterial_ulcer"),
    (r"surgical\s+site\s+infection|SSI|post.{0,5}op\s+wound","surgical_site_infection"),
    (r"\babscess\b",                                          "abscess"),
    (r"\bburn\b",                                             "burn"),
]

STAGES = [
    (r"[Ss]tage\s*(IV|4)\b", 4),
    (r"[Ss]tage\s*(III|3)\b", 3),
    (r"[Ss]tage\s*(II|2)\b", 2),
    (r"[Ss]tage\s*(I\b|1\b)", 1),
    (r"[Uu]nstageable|[Dd]eep\s+[Tt]issue", "unstageable"),
]

def _extract_from_text(text):
    if not text:
        return {}
    wound_type = None
    for pat, wtype in WOUND_TYPES:
        if re.search(pat, text, re.IGNORECASE):
            wound_type = wtype
            break
    stage = None
    if wound_type == "pressure_ulcer":
        for pat, s in STAGES:
            if re.search(pat, text):
                stage = s
                break
    location = None
    loc_m = re.search(r"[Ll]ocation\s*[:\-]\s*([^\n,\.\/]{3,50})", text)
    if loc_m:
        location = loc_m.group(1).strip()
    # Also try "Venous to [location]" pattern
    if not location:
        loc_m2 = re.search(r"(?:venous|wound)\s+(?:to|at|on)\s+([^\n,\.\/]{3,40})", text, re.IGNORECASE)
        if loc_m2:
            location = loc_m2.group(1).strip()
    drainage = None
    drain_m = re.search(r"[Dd]rainage\s*[:\-]?\s*([^\n,\.\/]{2,40})", text)
    if drain_m:
        drainage = _normalise_drainage(drain_m.group(1))
    if not drainage:
        drainage = _normalise_drainage(text)
    return {"wound_type": wound_type, "stage": stage, "location": location,
            "drainage": drainage, **_extract_measurements(text)}

def _parse_assessment_raw_json(raw):
    """
    Handles both assessment formats:
    1. Flat: {"wound_type": "pressure_ulcer", "length_cm": 3.2, ...}
    2. Nested: {"sections": [{"questions": [{"answer": "Venous to..."}]}]}
    """
    try:
        data = json.loads(raw) if isinstance(raw, str) else raw
    except Exception:
        return {}

    # Format 1: flat keys
    if data.get('wound_type') or data.get('length_cm'):
        return {
            "wound_type": data.get("wound_type"),
            "stage":      data.get("stage"),
            "location":   data.get("location"),
            "length_cm":  data.get("length_cm"),
            "width_cm":   data.get("width_cm"),
            "depth_cm":   data.get("depth_cm"),
            "drainage":   _normalise_drainage(data.get("drainage_amount")),
            "assessment_date": data.get("assessmentDate", ""),
        }

    # Format 2: nested sections/questions
    text = ""
    for section in data.get('sections', []):
        for q in section.get('questions', []):
            answer = q.get('answer', '')
            if answer:
                text += answer + "\n"

    if not text:
        return {}

    fields = _extract_from_text(text)
    fields['assessment_date'] = data.get('assessmentDate', '')
    return fields

def _detect_format(text, note_type):
    if note_type and "SPN" in str(note_type):
        if re.search(r"[Ll]ength\s*[:\-]", text):
            return "SOAP"
    if re.search(r"[Mm]eas\s*[:\-]?\s*[0-9]", text):
        return "Prose"
    if re.search(r"[Ww]ound\s*[#\-]?\s*2|[Ss]econdary\s+[Ww]ound", text):
        return "Multi-wound"
    return "Envive"

def _extract_with_llm(note_text, task="extract"):
    try:
        import anthropic
        client = anthropic.Anthropic()
        if task == "extract":
            prompt = f"""You are a clinical data extractor for wound care billing.
Extract ONLY these fields. Return valid JSON only, no explanation.
Keys: wound_type, stage, location, length_cm, width_cm, depth_cm, drainage_amount
Use null for missing fields.
wound_type options: pressure_ulcer, diabetic_foot_ulcer, venous_stasis_ulcer, arterial_ulcer, surgical_site_infection, abscess, burn, or null.
drainage_amount options: none, light, moderate, heavy, or null.
Note: {note_text[:2000]}"""
        else:
            prompt = f"""This note describes multiple wounds. Return ONLY the text
describing the primary wound (most severe or largest). Note: {note_text[:2000]}"""
        resp = client.messages.create(
            model="claude-sonnet-4-6", max_tokens=500,
            messages=[{"role": "user", "content": prompt}])
        raw = resp.content[0].text.strip()
        if task == "extract":
            data = json.loads(raw.replace("```json", "").replace("```", "").strip())
            return {"wound_type": data.get("wound_type"), "stage": data.get("stage"),
                    "location": data.get("location"),
                    "drainage": _normalise_drainage(data.get("drainage_amount")),
                    "length_cm": data.get("length_cm"),
                    "width_cm":  data.get("width_cm"),
                    "depth_cm":  data.get("depth_cm")}
        return {"primary_section": raw}
    except Exception as exc:
        log.warning(f"LLM extraction failed: {exc}")
        return {}

def extract_wound_data(patient):
    result = {"wound_type": None, "stage": None, "location": None,
              "length_cm": None, "width_cm": None, "depth_cm": None,
              "drainage": None, "source": None, "note_format": None, "confidence": "low"}

    # 1. Structured assessments — now handles nested format
    for a in sorted(patient.get("assessments", []),
                    key=lambda x: x.get("assessment_date", ""), reverse=True):
        raw = a.get("raw_json")
        if not raw:
            continue
        fields = _parse_assessment_raw_json(raw)
        if not fields.get("wound_type"):
            continue
        l, w, d = fields.get("length_cm"), fields.get("width_cm"), fields.get("depth_cm")
        result.update({
            "wound_type": fields.get("wound_type"),
            "stage":      fields.get("stage"),
            "location":   fields.get("location"),
            "length_cm":  l, "width_cm": w, "depth_cm": d,
            "drainage":   fields.get("drainage"),
            "source":     "assessment",
            "note_format":"structured",
            "confidence": "high" if all([l, w]) else "medium",
        })
        return result

    # 2. Progress notes
    for note in sorted(patient.get("notes", []),
                       key=lambda n: n.get("effective_date", ""), reverse=True):
        text = note.get("note_text", "") or ""
        note_type = note.get("note_type", "") or ""
        if not text.strip():
            continue
        fmt = _detect_format(text, note_type)
        if fmt == "Multi-wound":
            pick = _extract_with_llm(text, task="primary")
            parse_text = pick.get("primary_section", text)
        else:
            parse_text = text
        fields = _extract_from_text(parse_text)
        if not fields.get("wound_type"):
            if fmt == "Envive":
                llm_fields = _extract_with_llm(text, task="extract")
                if llm_fields.get("wound_type"):
                    result.update({**llm_fields, "source": "llm",
                                   "note_format": "Envive", "confidence": "medium"})
                    return result
            continue
        has_all = all(fields.get(k) for k in ["length_cm", "width_cm"])
        has_drn = bool(fields.get("drainage"))
        if has_all and has_drn:
            confidence = "high" if fmt in ("SOAP", "structured") else "medium"
        elif has_all or has_drn:
            confidence = "medium"
        else:
            confidence = "low"
        result.update({**fields, "source": "note",
                       "note_format": fmt, "confidence": confidence})
        return result
    return result

def compute_wound_trajectory(patient):
    points = []
    for a in patient.get("assessments", []):
        raw = a.get("raw_json")
        if not raw:
            continue
        try:
            fields = _parse_assessment_raw_json(raw)
            l, w  = fields.get("length_cm"), fields.get("width_cm")
            date  = fields.get("assessment_date") or a.get("assessment_date", "")
            if l and w and date:
                points.append({"date": str(date), "area": round(float(l) * float(w), 2)})
        except Exception:
            continue
    points = sorted(points, key=lambda x: x["date"])
    visit_count = len(points)
    if visit_count < 2:
        return {"visit_count": visit_count, "wound_trend": "insufficient_data",
                "area_change_pct": None, "compliance_flag": False,
                "measurement_jump_flag": False, "high_frequency_flag": False}
    first_area = points[0]["area"]
    last_area  = points[-1]["area"]
    delta_pct  = round((last_area - first_area) / first_area * 100, 1) if first_area else None
    if delta_pct is None:           trend = "insufficient_data"
    elif delta_pct <= -10:          trend = "improving"
    elif delta_pct >= 10:           trend = "worsening"
    else:                           trend = "stalled"
    compliance_flag = visit_count >= 3 and trend in ("stalled", "worsening")
    measurement_jump_flag = any(
        points[i+1]["area"] > points[i]["area"] * 1.5
        for i in range(len(points) - 1))
    high_frequency_flag = False
    if visit_count >= 4:
        try:
            from datetime import datetime
            dates = [datetime.fromisoformat(str(p["date"])) for p in points]
            span  = (dates[-1] - dates[0]).days
            high_frequency_flag = span <= 30
        except Exception:
            pass
    return {"visit_count": visit_count, "wound_trend": trend,
            "area_change_pct": delta_pct, "compliance_flag": compliance_flag,
            "measurement_jump_flag": measurement_jump_flag,
            "high_frequency_flag": high_frequency_flag}

Overwriting extract.py

## Step 6 — Eligibility & Routing Engine

Produces one routing decision per patient with a plain-English reason.

**Three decisions:**
- `auto_accept` — All required fields present, Medicare Part B active, no compliance flags
- `flag_for_review` — Data incomplete, ambiguous, or compliance risk detected
- `reject` — Reliably confirmed ineligible (non-MCB payer, no wound found)

**9-Tier Flag Priority System (research-backed):**

| Priority | Flag | Research Source |
|----------|------|-----------------|
| 1 | No Medicare Part B | API coverage records |
| 2 | API fetch failure | fetch_status tracking |
| 3 | No wound type extracted | Notes/assessments |
| 4 | Envive + missing fields | Note format detection |
| 5 | Missing required fields | Extraction output |
| 6 | No wound ICD-10 diagnosis | DOJ 2025 FCA settlements |
| 7 | New admission + Stage 3/4 | RAC audit patterns |
| 8 | Stalled/worsening wound 3+ visits | OIG healing progress requirement |
| 9 | High visit frequency / Measurement jump | Inside the False Claims Act 2026 |

**Core principle:**  
*"We never treat failed API calls as missing clinical facts. If an endpoint fails after retries,  
we store the partial record and route to review — not reject. Final decisions only when  
required data was successfully fetched."*

In [18]:
%%writefile eligibility.py
from datetime import datetime, timezone

WOUND_ICD10_PREFIXES = ['L89', 'L97', 'L98', 'E11.6', 'I83', 'T79']

# depth_cm removed — real API data is often 2D only
REQUIRED_FIELDS = ["wound_type", "length_cm", "width_cm", "drainage"]

def has_active_mcb(coverage_records):
    today = datetime.now(timezone.utc).date()
    for c in coverage_records:
        if c.get("payer_code") != "MCB":
            continue
        eff_to = c.get("effective_to")
        if eff_to is None:
            return True
        try:
            end = datetime.fromisoformat(eff_to.replace("Z", "+00:00")).date()
            if end >= today:
                return True
        except Exception:
            continue
    return False

def _missing_fields(wound):
    return [f for f in REQUIRED_FIELDS if not wound.get(f)]

def _has_wound_icd10(diagnoses):
    for d in diagnoses:
        if d.get("clinical_status") != "active":
            continue
        code = d.get("icd10_code", "")
        if any(code.startswith(p) for p in WOUND_ICD10_PREFIXES):
            return True
    return False

def route_patient(patient, wound, trajectory):
    fetch  = patient.get("fetch_status", {})
    payer  = patient.get("primary_payer_code", "")
    mcb    = has_active_mcb(patient.get("coverage", []))
    cov_failed    = fetch.get("coverage")    == "failed"
    notes_failed  = fetch.get("notes")       == "failed"
    assess_failed = fetch.get("assessments") == "failed"

    if cov_failed:
        return {"decision": "flag_for_review",
                "reason": "Could not verify Medicare Part B coverage — API sync incomplete. Do not route to billing until coverage is confirmed."}
    if not mcb:
        return {"decision": "reject",
                "reason": f"No active Medicare Part B. Primary payer: {payer}. Not eligible for wound care billing."}
    if notes_failed and assess_failed:
        return {"decision": "flag_for_review",
                "reason": "Medicare Part B confirmed but wound data could not be fetched. Do not bill until wound documentation is verified."}
    if not wound.get("wound_type"):
        return {"decision": "reject",
                "reason": "Could not extract wound type from available notes or assessments. Do not route to billing."}

    missing = _missing_fields(wound)
    if wound.get("note_format") == "Envive" and missing:
        return {"decision": "flag_for_review",
                "reason": f"Unstructured Envive note — could not reliably extract: {', '.join(missing)}. Clinician review required."}
    if missing:
        return {"decision": "flag_for_review",
                "reason": f"Medicare Part B confirmed but documentation incomplete. Missing: {', '.join(missing)}."}
    if not _has_wound_icd10(patient.get("diagnoses", [])):
        return {"decision": "flag_for_review",
                "reason": "No active wound-related ICD-10 diagnosis on file. Medical necessity unsupported without a matching diagnosis code."}
    if patient.get("is_new_admission") and wound.get("stage") in (3, 4, "unstageable"):
        return {"decision": "flag_for_review",
                "reason": f"New admission with Stage {wound.get('stage')} wound. Document whether wound is facility-acquired before billing."}
    if trajectory.get("compliance_flag"):
        visits = trajectory["visit_count"]
        trend  = trajectory["wound_trend"]
        chg    = trajectory.get("area_change_pct")
        chg_s  = f" ({chg:+.1f}% area change)" if chg is not None else ""
        return {"decision": "flag_for_review",
                "reason": f"Wound is '{trend}' across {visits} visits{chg_s}. Medicare requires documented healing progress — review before billing."}
    if trajectory.get("high_frequency_flag"):
        return {"decision": "flag_for_review",
                "reason": f"{trajectory['visit_count']} visits in 30 days. Unusually high billing frequency — review before submitting."}
    if trajectory.get("measurement_jump_flag"):
        return {"decision": "flag_for_review",
                "reason": "Wound area increased more than 50% between visits. May indicate measurement error — verify before billing."}

    wtype     = (wound.get("wound_type") or "").replace("_", " ").title()
    stage_str = f" Stage {wound['stage']}" if wound.get("stage") else ""
    loc_str   = f" at {wound['location']}" if wound.get("location") else ""
    trend_str = ""
    if trajectory.get("wound_trend") == "improving":
        chg = trajectory.get("area_change_pct")
        trend_str = f" Wound trending toward healing ({chg:+.1f}% area reduction)." if chg else " Wound trending toward healing."
    return {"decision": "auto_accept",
            "reason": f"Active Medicare Part B. {wtype}{stage_str}{loc_str}. All required fields documented.{trend_str} Safe to route to billing."}

def build_output_row(patient, wound, trajectory):
    routing = route_patient(patient, wound, trajectory)
    fetch   = patient.get("fetch_status", {})
    return {
        "patient_id":          patient.get("patient_id"),
        "facility_id":         patient.get("facility_id"),
        "name":                f"{patient.get('first_name','')} {patient.get('last_name','')}".strip(),
        "dob":                 patient.get("birth_date"),
        "is_new_admission":    patient.get("is_new_admission"),
        "mcb_active":          has_active_mcb(patient.get("coverage", [])),
        "primary_payer":       patient.get("primary_payer_code"),
        "wound_type":          wound.get("wound_type"),
        "stage":               wound.get("stage"),
        "location":            wound.get("location"),
        "length_cm":           wound.get("length_cm"),
        "width_cm":            wound.get("width_cm"),
        "depth_cm":            wound.get("depth_cm"),
        "drainage":            wound.get("drainage"),
        "note_format":         wound.get("note_format"),
        "extraction_source":   wound.get("source"),
        "confidence":          wound.get("confidence"),
        "visit_count":         trajectory.get("visit_count"),
        "wound_trend":         trajectory.get("wound_trend"),
        "area_change_pct":     trajectory.get("area_change_pct"),
        "compliance_flag":     trajectory.get("compliance_flag"),
        "high_frequency_flag": trajectory.get("high_frequency_flag"),
        "measurement_jump":    trajectory.get("measurement_jump_flag"),
        "fetch_coverage":      fetch.get("coverage"),
        "fetch_notes":         fetch.get("notes"),
        "fetch_assessments":   fetch.get("assessments"),
        "decision":            routing["decision"],
        "reason":              routing["reason"],
    }

Overwriting eligibility.py

## Step 7 — Set Anthropic API Key (for LLM Extraction)

Required for LLM fallback on Envive notes.  
Get your key from https://console.anthropic.com

In [19]:
import os
os.environ["ANTHROPIC_API_KEY"] = "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"  # Replace with your key
print("API key set")

API key set

## Step 8 — Run Full Pipeline

Runs extraction and eligibility on all ingested patients.  
Saves results to `output/eligibility_output.csv`.

In [20]:
import importlib
import extract, eligibility
importlib.reload(extract)
importlib.reload(eligibility)

import pandas as pd
from extract import extract_wound_data, compute_wound_trajectory
from eligibility import build_output_row

rows = []
for patient in patients:
    wound      = extract_wound_data(patient)
    trajectory = compute_wound_trajectory(patient)
    row        = build_output_row(patient, wound, trajectory)
    rows.append(row)

df = pd.DataFrame(rows)
df.to_csv('output/eligibility_output.csv', index=False)

print("=" * 50)
print("PIPELINE RESULTS")
print("=" * 50)
print(f"Total patients processed : {len(df)}")
print(f"Active Medicare Part B   : {int(df['mcb_active'].sum())}")
print()
print("Routing decisions:")
print(df['decision'].value_counts().to_string())
print()
print(f"Compliance risk flags    : {int(df['compliance_flag'].fillna(False).sum())}")
print(f"High frequency flags     : {int(df['high_frequency_flag'].fillna(False).sum())}")
print(f"Measurement jump flags   : {int(df['measurement_jump'].fillna(False).sum())}")
print()
print("Wound types (auto-accept patients):")
print(df[df['decision']=='auto_accept']['wound_type'].value_counts().to_string())

2026-06-28 14:17:45,676 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:17:45,680 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:17:47,855 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:17:50,625 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:17:50,629 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:17:59,231 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:18:01,977 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:18:01,979 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:18:04,367 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:18:09,141 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:18:09,145 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:18:11,860 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:18:11,864 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:18:14,760 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:18:14,763 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:18:17,706 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:18:17,710 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:18:20,641 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:18:20,643 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:18:23,298 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:18:23,301 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:18:26,300 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:18:26,307 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:18:29,609 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:18:29,611 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:18:32,585 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:18:32,589 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:18:45,506 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:18:45,508 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:18:48,355 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:18:48,360 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:18:51,002 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:18:51,007 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:18:56,390 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:18:56,398 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:18:58,483 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:19:01,148 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:19:01,152 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:19:03,811 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:19:03,815 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:19:06,397 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:19:06,401 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:19:09,409 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:19:09,413 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:19:12,094 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:19:12,098 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:19:14,863 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:19:14,867 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:19:16,925 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:19:19,582 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:19:19,586 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:19:22,267 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:19:22,270 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:19:25,262 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:19:25,268 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:19:27,253 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:19:30,527 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2026-06-28 14:19:30,531 WARNING LLM extraction failed: 'list' object has no attribute 'get'
2026-06-28 14:19:32,446 INFO HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"

==================================================
PIPELINE RESULTS
==================================================
Total patients processed : 300
Active Medicare Part B   : 145

Routing decisions:
decision
reject             180
flag_for_review     69
auto_accept         51

Compliance risk flags    : 0
High frequency flags     : 0
Measurement jump flags   : 0

Wound types (auto-accept patients):
wound_type
surgical_site_infection    27
pressure_ulcer             11
venous_stasis_ulcer         9
diabetic_foot_ulcer         4

## Step 9 — Preview Output

Sample of auto-accept patients ready for billing.

In [23]:
print("AUTO-ACCEPT — Safe to bill:")
accept = df[df['decision']=='auto_accept']
display(accept[['patient_id','wound_type','stage','location',
                'length_cm','width_cm','drainage','wound_trend','reason']].head(10))

print()
print("FLAG FOR REVIEW — Need attention:")
flag = df[df['decision']=='flag_for_review']
display(flag[['patient_id','wound_type','decision','reason']].head(10))

AUTO-ACCEPT — Safe to bill:

,patient_id,wound_type,stage,location,length_cm,width_cm,drainage,wound_trend,reason
2,FA-005,venous_stasis_ulcer,NaN,Right lower leg,3.1,3.4,moderate,insufficient_data,Active Medicare Part B. Venous Stasis Ulcer at...
5,FA-009,surgical_site_infection,NaN,None,5.3,4.5,moderate,insufficient_data,Active Medicare Part B. Surgical Site Infectio...
9,FA-006,surgical_site_infection,NaN,None,2.7,1.5,heavy,insufficient_data,Active Medicare Part B. Surgical Site Infectio...
14,FA-016,venous_stasis_ulcer,NaN,Right lower leg,7.6,4.2,moderate,insufficient_data,Active Medicare Part B. Venous Stasis Ulcer at...
16,FA-020,surgical_site_infection,NaN,None,3.2,2.3,none,insufficient_data,Active Medicare Part B. Surgical Site Infectio...
17,FA-017,surgical_site_infection,NaN,None,6.3,5.7,moderate,insufficient_data,Active Medicare Part B. Surgical Site Infectio...
36,FA-039,diabetic_foot_ulcer,NaN,right plantar,1.4,1.7,moderate,insufficient_data,Active Medicare Part B. Diabetic Foot Ulcer at...
37,FA-034,pressure_ulcer,2.0,None,3.0,2.2,moderate,insufficient_data,Active Medicare Part B. Pressure Ulcer Stage 2...
38,FA-040,surgical_site_infection,NaN,None,3.0,0.9,light,insufficient_data,Active Medicare Part B. Surgical Site Infectio...
44,FA-038,diabetic_foot_ulcer,NaN,left plantar,3.1,1.7,none,insufficient_data,Active Medicare Part B. Diabetic Foot Ulcer at...

FLAG FOR REVIEW — Need attention:

,patient_id,wound_type,decision,reason
0,FA-001,pressure_ulcer,flag_for_review,New admission with Stage 3 wound. Document whe...
7,FA-011,pressure_ulcer,flag_for_review,Medicare Part B confirmed but documentation in...
8,FA-012,abscess,flag_for_review,Medicare Part B confirmed but documentation in...
12,FA-013,abscess,flag_for_review,No active wound-related ICD-10 diagnosis on fi...
19,FA-021,surgical_site_infection,flag_for_review,No active wound-related ICD-10 diagnosis on fi...
20,FA-024,pressure_ulcer,flag_for_review,Medicare Part B confirmed but documentation in...
22,FA-026,surgical_site_infection,flag_for_review,No active wound-related ICD-10 diagnosis on fi...
23,FA-027,abscess,flag_for_review,Medicare Part B confirmed but documentation in...
26,FA-025,pressure_ulcer,flag_for_review,Medicare Part B confirmed but documentation in...
39,FA-041,surgical_site_infection,flag_for_review,No active wound-related ICD-10 diagnosis on fi...

## Step 10 — Launch Dashboard

Run this in a Terminal (not in Jupyter):
```bash
cd /Users/richashiny
streamlit run dashboard.py
```
Then open http://localhost:8501

In [24]:
%%writefile dashboard.py
import pandas as pd
import streamlit as st
from pathlib import Path

OUTPUT_PATH = Path("output/eligibility_output.csv")

st.set_page_config(page_title="ABI Frameworks - Wound Care Billing", page_icon="", layout="wide")

if not OUTPUT_PATH.exists():
    st.error("No output found. Run the pipeline first.")
    st.stop()

df = pd.read_csv(OUTPUT_PATH)
df["compliance_flag"]     = df["compliance_flag"].fillna(False).astype(bool)
df["high_frequency_flag"] = df["high_frequency_flag"].fillna(False).astype(bool)
df["measurement_jump"]    = df["measurement_jump"].fillna(False).astype(bool)

view = st.sidebar.radio("View", ["Biller View", "Technical View"])

if view == "Biller View":
    st.title("Wound Care Billing - Today's Work Queue")
    st.caption("Powered by ABI Frameworks - Medicare Part B - PointClickCare data")

    accept = df[df["decision"] == "auto_accept"]
    flag   = df[df["decision"] == "flag_for_review"]
    reject = df[df["decision"] == "reject"]

    c1, c2, c3 = st.columns(3)
    c1.markdown(f"""
    <div style='background:#d4edda;padding:24px;border-radius:12px;text-align:center'>
    <h1 style='color:#155724;margin:0'>{len(accept)}</h1>
    <h3 style='color:#155724;margin:4px 0'>Submit Today</h3>
    <p style='color:#155724;margin:0'>All required fields present. Safe to bill Medicare.</p>
    </div>""", unsafe_allow_html=True)

    c2.markdown(f"""
    <div style='background:#fff3cd;padding:24px;border-radius:12px;text-align:center'>
    <h1 style='color:#856404;margin:0'>{len(flag)}</h1>
    <h3 style='color:#856404;margin:4px 0'>Review First</h3>
    <p style='color:#856404;margin:0'>Something needs checking. Do not bill yet.</p>
    </div>""", unsafe_allow_html=True)

    c3.markdown(f"""
    <div style='background:#f8d7da;padding:24px;border-radius:12px;text-align:center'>
    <h1 style='color:#721c24;margin:0'>{len(reject)}</h1>
    <h3 style='color:#721c24;margin:4px 0'>Do Not Bill</h3>
    <p style='color:#721c24;margin:0'>Not eligible for Medicare Part B wound care billing.</p>
    </div>""", unsafe_allow_html=True)

    st.divider()

    risk = df[df["compliance_flag"] | df["high_frequency_flag"] | df["measurement_jump"]]
    if not risk.empty:
        st.markdown(f"### Audit Risk - {len(risk)} patients need attention before billing")
        st.caption("These patients are technically billable but show patterns Medicare auditors flag.")
        for _, row in risk.iterrows():
            st.markdown(f"""
            <div style='background:#fff3cd;border-left:4px solid #ffc107;
                        padding:14px 18px;border-radius:6px;margin-bottom:10px'>
            <b>{row['patient_id']} - {str(row.get('name','')).title()}</b><br>
            <span style='color:#555'>{str(row.get('wound_type','')).replace('_',' ').title()}
            {' Stage '+str(int(row['stage'])) if pd.notna(row.get('stage')) else ''}
            {' - '+str(row.get('location','')) if pd.notna(row.get('location')) else ''}</span><br>
            <span style='color:#856404'>{row['reason']}</span>
            </div>""", unsafe_allow_html=True)
        st.divider()

    if not flag.empty:
        st.markdown(f"### Review Queue - {len(flag)} patients")
        for _, row in flag.iterrows():
            st.markdown(f"""
            <div style='background:#fffdf0;border-left:4px solid #ffc107;
                        padding:12px 16px;border-radius:6px;margin-bottom:8px'>
            <b>{row['patient_id']} - {str(row.get('name','')).title()}</b>
            <span style='color:#888;font-size:0.85em'> - {str(row.get('wound_type','')).replace('_',' ').title()}</span><br>
            <span style='color:#666'>{row['reason']}</span>
            </div>""", unsafe_allow_html=True)
        st.divider()

    if not accept.empty:
        st.markdown(f"### Ready to Submit - {len(accept)} patients")
        show_cols = ["patient_id","name","wound_type","stage","location",
                     "length_cm","width_cm","depth_cm","drainage","wound_trend"]
        show_cols = [c for c in show_cols if c in accept.columns]
        st.dataframe(accept[show_cols], use_container_width=True, height=400)

else:
    st.title("Pipeline Technical View")
    st.caption("For compliance officers and data teams")

    total  = len(df)
    mcb    = df["mcb_active"].sum()
    accept = (df["decision"]=="auto_accept").sum()
    flag   = (df["decision"]=="flag_for_review").sum()
    reject = (df["decision"]=="reject").sum()
    comp   = df["compliance_flag"].sum()

    col1,col2,col3,col4,col5 = st.columns(5)
    col1.metric("Total Patients",   total)
    col2.metric("Medicare Part B",  int(mcb))
    col3.metric("Auto-Accept",      int(accept))
    col4.metric("Flag for Review",  int(flag))
    col5.metric("Compliance Risk",  int(comp))

    st.divider()
    col_a, col_b = st.columns(2)

    with col_a:
        st.subheader("Routing Decisions")
        counts = df["decision"].value_counts().reset_index()
        counts.columns = ["Decision","Count"]
        st.bar_chart(counts.set_index("Decision"))

    with col_b:
        st.subheader("Decisions by Facility")
        fac = df.groupby(["facility_id","decision"]).size().unstack(fill_value=0)
        st.bar_chart(fac)

    st.divider()
    st.subheader("Note Format vs Confidence")
    if "note_format" in df.columns and "confidence" in df.columns:
        fmt_conf = df.groupby(["note_format","confidence"]).size().unstack(fill_value=0)
        st.bar_chart(fmt_conf)

    st.divider()
    st.sidebar.header("Filters")
    dec_filter = st.sidebar.multiselect(
        "Decision", ["auto_accept","flag_for_review","reject"],
        default=["auto_accept","flag_for_review","reject"])
    fac_filter = st.sidebar.multiselect(
        "Facility", sorted(df["facility_id"].dropna().unique().tolist()),
        default=sorted(df["facility_id"].dropna().unique().tolist()))

    mask = df["decision"].isin(dec_filter) & df["facility_id"].isin(fac_filter)
    filtered = df[mask]

    st.subheader(f"Full Patient Table ({len(filtered)} patients)")

    def colour_decision(val):
        m = {"auto_accept":"background-color:#d4edda;color:#155724",
             "flag_for_review":"background-color:#fff3cd;color:#856404",
             "reject":"background-color:#f8d7da;color:#721c24"}
        return m.get(val,"")

    display_cols = ["patient_id","name","facility_id","wound_type","stage",
                    "length_cm","width_cm","depth_cm","drainage",
                    "visit_count","wound_trend","compliance_flag","decision","reason"]
    display_cols = [c for c in display_cols if c in filtered.columns]
    styled = filtered[display_cols].style.applymap(colour_decision, subset=["decision"])
    st.dataframe(styled, use_container_width=True, height=500)

st.divider()
st.caption("ABI Frameworks - Medicare Part B Wound Care Billing - Built on PointClickCare data")

Overwriting dashboard.py

In [27]:
# OPTIMIZATION 1: Cache coverage and diagnoses
# These fields rarely change — no need to re-fetch every run
# At 1M patients this saves ~60% of API calls


import json
from pathlib import Path
from datetime import datetime

def build_coverage_cache(patients):
    """
    Extract coverage and diagnoses from already-fetched patients
    and store with a timestamp. On next run, skip these API calls
    if cache is less than 7 days old.
    """
    cache = {}
    for p in patients:
        pid = p['patient_id']
        cache[pid] = {
            'coverage':   p.get('coverage', []),
            'diagnoses':  p.get('diagnoses', []),
            'cached_at':  datetime.now().isoformat(),
            'payer_code': p.get('primary_payer_code')
        }

    Path('data').mkdir(exist_ok=True)
    with open('data/coverage_cache.json', 'w') as f:
        json.dump(cache, f)

    print(f"Cached coverage + diagnoses for {len(cache)} patients")
    print("Next run will skip /coverage and /diagnoses API calls")
    print(f"Estimated calls saved next run: {len(cache) * 2}")

build_coverage_cache(patients)

Cached coverage + diagnoses for 300 patients
Next run will skip /coverage and /diagnoses API calls
Estimated calls saved next run: 600

In [26]:
# OPTIMIZATION 2: Incremental Sync
# Only fetch patients modified since last run
# At 1M patients, ~5,000 change daily vs 1,000,000 full fetch
# Your pipeline already supports this via the --since parameter

from datetime import datetime, timedelta

# Simulate: only fetch patients modified in the last 24 hours
since_timestamp = (datetime.now() - timedelta(hours=24)).isoformat()

print("INCREMENTAL SYNC DEMO")
print("=" * 45)
print(f"Last run:     {since_timestamp}")
print(f"Full sync:    893 API calls for 300 patients")
print()

# Count how many patients would be fetched
import json
with open('data/raw_patients.json') as f:
    all_patients = json.load(f)

recent = [p for p in all_patients
          if p.get('last_modified_at', '') >= since_timestamp]

print(f"Modified in last 24hrs: {len(recent)} patients")
print(f"API calls for delta:    {len(recent) * 4} calls")
print(f"Calls saved vs full:    {893 - (len(recent) * 4)}")
print()
print("At 1M patients scale:")
daily_change_rate = 0.005  # 0.5% of patients change daily
daily_changes = int(1_000_000 * daily_change_rate)
full_sync_calls = 1_000_000 * 4
incremental_calls = daily_changes * 4
print(f"  Full sync:        {full_sync_calls:,} calls/day")
print(f"  Incremental sync: {incremental_calls:,} calls/day")
print(f"  Reduction:        {(1 - incremental_calls/full_sync_calls)*100:.0f}%")

INCREMENTAL SYNC DEMO
=============================================
Last run:     2026-06-27T14:39:10.391576
Full sync:    893 API calls for 300 patients

Modified in last 24hrs: 0 patients
API calls for delta:    0 calls
Calls saved vs full:    893

At 1M patients scale:
  Full sync:        4,000,000 calls/day
  Incremental sync: 20,000 calls/day
  Reduction:        100%